### ISSUE TITLE
Speedup cross architecture docker builds

### ISSUE THREAD

**Issue by dumbasPL** [Ravinou/borgwarehouse#107]
The CI build times for Docker images could be sped up drastically (we're talking minutes instead of hours) by building the javascript code on the native architecture and only building the final stage on the target architecture. Javascript should be architecture-agnostic.

It is also possible to set up GitHub actions to build each architecture on a separate job and then merge them in the end under a single docker tag ([example on one of my repos](https://github.com/dumbasPL/aero2solver/blob/master/.github/workflows/docker.yml)). This allows for a further speed increase of almost 3x (if we're building for 3 different architectures)

I'll try to make a PR for this. This way we could support many architectures without having to wait hours for a build to finish.

**Comment by Ravinou** [comment]
An other contributor for docker part, @dhenry123 made a MR yesterday for information : https://github.com/Ravinou/borgwarehouse/pull/106

But the build isn't work for the moment. I don't have time this week-end to look at it. If you want to make an MR, please, do it on develop branch. Thanks.

**Comment by dumbasPL** [comment]
I'm trying to do it on the `develop` branch but it seems like you merged a "work in progress" mr (WTF, why?), and some things are straight-up broken (like ssh host key generation). I'll try to fix what I can but I'm not sure what @dhenry123 wanted to achieve exactly. Also, he changed the base image from Debian to Alpine without even mentioning it in the commit/mr. Not saying this is a bad idea, smaller images are a good thing, but now we have to build jc ourselves, and without an easy way to cross-compile things installed using pip this will cost us quite a bit in build time. I'll try to submit a package for jc to Alpine but it will take a while until it appears in stable repos.

**Comment by dhenry123** [comment]
I'm trying to answer #94

**Comment by Ravinou** [comment]
Hi, I backtracked on several commits on the branch develop because it was causing too many problems and an impossible build in the Github CI (which I couldn't find the origin of because the local build was working 🤷‍♂️). I don't know `nss_wrapper` and I don't have the debug skills. 

@dhenry123 has a specific use case, with kubernetes, [his commit is functional on his infrastructure](https://github.com/Ravinou/borgwarehouse/pull/106). But this case (and its infrastructure) is not the most common and it is "enterprise" oriented, so [you can contact him](https://www.mytinydc.com/en/contact/) or look at his blog for more information on this subject.

I've gone back to something simpler, using supervisord as recommended in the docker documentation works well, there are no more zombie processes, and SSH and application logs are now in a separate volume. **And cron is now out of docker.**

BorgWarehouse v2.1 will be released shortly with these modifications (see branch develop).

Thank you both for your help and contributions.
