### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by GabomaGeek** [Ravinou/borgwarehouse#109]
Hello.
I want to update to the v2.0 but i got this error
 ```
error: Your local changes to the following files would be overwritten by merge:
        helpers/shells/recreateRepoConfigFile.sh
        package.json
Please commit your changes or stash them before you merge.
Aborting
``` 
when execute git pull. 
Does anyone know how to resolve this error ?
Thank you

**Comment by Ravinou** [comment]
Hi ! Sorry for the delay.

This error is purely a git error. It means that both files have local modifications. If you have made specific changes to them, I advise you to remove them from the directory and save them before resynchronizing the directory.

Please note that there is currently no specific procedure for switching from v1.x to v2. It's a breakingchange due to borgbackup specifications. These changes were necessary in order to adhere as closely as possible to the borgbackup documentation and enable docker support.

You can stay with v1, or install v2 on the side and recreate your repositories, or migrate manually (but this requires an excellent knowledge of borg, I don't have time to make a documentation, each one moreover having a specific installation).

[You can see what's new here.](https://borgwarehouse.com/docs/admin-manual/how-to-update/#whats-new-in-v2-)
