### ISSUE TITLE
Help on installation

### ISSUE THREAD

**Issue by GabomaGeek** [Ravinou/borgwarehouse#124]
Hello everyone. I followed the recommendations to install borg on windows and everything worked fine. But one day the Windows machine had a problem and after restoring it, borgwarehouse displayed an API error. I thought it was related to the Windows machine disconnection problem so I manually deleted the directory in config/repo.json, but still nothing. Looking around a bit I saw this error
`SyntaxError: Unexpected string in JSON at position 1869
at JSON.parse (<anonymous>)
at handler (/home/borgwarehouse/borgwarehouse/.next/server/pages/api/repo.js:88:29)`
The error indicates this line ` repoList = JSON.parse(repoList);` in the file.
Anyone have an idea how to solve it?
Thanks in advance.

**Comment by Ravinou** [comment]
Hi @GabomaGeek I think you lose some informations because of your windows restoring. I've never used the linux system under windows. 

What I can tell you is that the `repo.json` file contains data about your repositories. If you've lost this file, you'll need to rebuild it : 
- in `v1.x.x` : [read the comment in this shell and use it](https://github.com/Ravinou/borgwarehouse/blob/v1.6.0/helpers/shells/recreateRepoConfigFile.sh) to rebuild a repo.json
- in `v2.x.x` : the `repo.json` file is versioned, [follow this guide](https://borgwarehouse.com/docs/help/faq/#i-lose-the-repojson-file) to restore it.

If you want to start from scratch, the application at least needs a repo.json file containing just an ampty array : `[]`

**Comment by GabomaGeek** [comment]
I want to start from scratch. How can i uninstall the entire application before install it again ?

**Comment by Ravinou** [comment]
What is your environment ? Docker or classic installation on Debian like ?

**Comment by GabomaGeek** [comment]
Classic installation on ubuntu

> What is your environment ? Docker or classic installation on Debian like ?

**Comment by Ravinou** [comment]
@GabomaGeek If you want to reinstall everything, the best option is to start from scratch. 

To do this, you can empty the contents of `/home/borgwarehouse` to create a blank folder (backup only the **.env.local** file if you want to keep the same). Your old backups are in `/var/borgwarehouse` (for v1.x.x), but you can also delete them if you don't want them anymore.

Once you've cleaned up your `/home/borgwarehouse` directory, you can restart an installation by following the documentation for baremetal installations [here](https://borgwarehouse.com/docs/admin-manual/debian-installation/).

Please keep me informed, otherwise I'll close the issue if everything's ok with you. Have a nice Sunday 😉

**Comment by GabomaGeek** [comment]
I start a fresh install with version 2. When i want to create a repository, but i got an error `undifined` and the repository is not created. But when i read the `borgware/.ssh/auhoryzed_keys`, i see informations about the repository that was not created.

**Comment by Ravinou** [comment]
Hi @GabomaGeek , I need more context and a possible error log to help you please.

**Comment by GabomaGeek** [comment]
@Ravinou this is the result i took form syslog 
`Feb 13 13:36:13 borgwarehouse npm[4007]:     at ChildProcess.exithandler (node:child_process:419:12)
Feb 13 13:36:13 borgwarehouse npm[4007]:     at ChildProcess.emit (node:events:514:28)
Feb 13 13:36:13 borgwarehouse npm[4007]:     at maybeClose (node:internal/child_process:1091:16)
Feb 13 13:36:13 borgwarehouse npm[4007]:     at Socket.<anonymous> (node:internal/child_process:449:11)
Feb 13 13:36:13 borgwarehouse npm[4007]:     at Socket.emit (node:events:514:28)
Feb 13 13:36:13 borgwarehouse npm[4007]:     at Pipe.<anonymous> (node:net:323:12) {
Feb 13 13:36:13 borgwarehouse npm[4007]:   code: 3,
Feb 13 13:36:13 borgwarehouse npm[4007]:   killed: false,
Feb 13 13:36:13 borgwarehouse npm[4007]:   signal: null,
Feb 13 13:36:13 borgwarehouse npm[4007]:   cmd: '/home/borgwarehouse/app/helpers/shells/createRepo.sh "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCTj7VBqhAoOSPXafA5m1c7w/H6yCgtBkz96l7QauELE993YOnG4KBGs6p78zMkYxQkENq8wGjaM73Ji7UzVcnFktDQgiONxo0kde9GHLddsxhPKUPfIT1+m9B4T2NQnWq/yjFSCyA+U8gUE48CeRdK1b7G2tgRDBh3w9hMvMxbF5cdJEp3IgB3vF21flcuEI/FkSi+fhPY0eBCI1KIQv63YJJPWa4U5pqESO5h8yIEMlw3MsnXrrJhBUHTdJengnvgySAuLmmSXjWfbKZTT8Jlsu7d1KyIfWSnbpeQ+xGnte5rddKBpj4hJy0PxcZAkzg1c7/amGlGwkAG8Zf05AB296QsLP7Uc8ZQtcoNQ+ytQO6Z7cFR6pqNipjfXemJWsvXM3PgUmw1gR8lPumzqVdoRev2e8hevhp3hfY4DUyQj78FeMBVZ9bJqPliLNMdKsJ3gdAKZjse5ERS2yS1U2K6Pt+AkAjyqa9OOiuD30CKggAfdSQNnXULYT0aqohUcps= cermel@redcapserver" 68',
Feb 13 13:36:13 borgwarehouse npm[4007]:   stdout: 'SSH pub key already present in authorized_keys',
Feb 13 13:36:13 borgwarehouse npm[4007]:   stderr: ''
Feb 13 13:36:13 borgwarehouse npm[4007]: }`

**Comment by Ravinou** [comment]
Hi, sorry for delay.

Your error says "'SSH pub key already present in authorized_keys'". Clean your authorized_keys please, it had to match with your current repo on borgwarehouse. And [you can't use a public key twice](https://borgwarehouse.com/docs/admin-manual/how-to-update/#whats-new-in-v2-).

**Comment by GabomaGeek** [comment]
Now, i can add repository. But when i try to initialize a repository, the system request the password for the user borgwarehouse but the user does not have one.

**Comment by Ravinou** [comment]
If the system asks you for a password, the SSH public key has not been found. So there's a configuration problem. You can check whether the key is in the file.

**Comment by GabomaGeek** [comment]
The key is in the file. I can connect via ssh to the borgwarehouse VM without being asked for password. And the key is also in `/home/borgwarehouse/.ssh/authorized_keys`

**Comment by Ravinou** [comment]
It's really difficult for me to help you without more detailed information.

**Comment by GabomaGeek** [comment]
I finally got the application works. I previously install Borgwarehouse on ubuntu and that worked i fine but since an issue, even a reinstallation did not resolve the issue and the password of the user borgwarehouse was always asked on archive initialization. So i decide to do the installation on debian and everything is now working properly.
