### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by rugk** [Ravinou/borgwarehouse#162]
I did not find any `spec`/`test`/`tst` files, so I guess I'd ask for the obvious thing: unit tests.

They ease contributing and make sure the software is maintainable in the future too. Also, if done properly, one can then follow a test-drove-development approach for making good software.

As you seem to use React, https://create-react-app.dev/docs/running-tests/ may be a good guide to get started, but I have not really much experience in React, so take this with a grain of salt.

**Comment by Ravinou** [comment]
Hi @rugk ! In my roadmap, I intend to upgrade BorgWarehouse with : 
- Typescript
- unit tests (Jest)
- e2e tests (Playwright)

I'm a firm believer in TDD, and I'll get around to it eventually. I'm starting this approach little by little on professional projects.

Unfortunately, as with new features, I work a lot and weekends and evenings aren't enough to do everything I'd like to do on BorgWarehouse. However, I'm in no hurry and BorgWarehouse is making good progress month after month, so a little more patience and it will come!

Thanks for your advice and for your attention to BorgWarehouse. I'm closing this issue because it's on my roadmap.
