### ISSUE TITLE
Repo API with Token key

### ISSUE THREAD

**Issue by rarrais** [Ravinou/borgwarehouse#179]
The possibility to access the API for repository management with an ```API_KEY``` (similar to the existing ```CRONJOB_KEY```) would open up automation possibilities for managing repositories (e.g., automatically adding new repositories; refreshing the SSH Public Key of an already configured repository). 

In the proposed scenario, the existing credentials-based authentication would still be supported, but augmented with an alternative (token key-based) method.

The main reason for the request is that I would like to start working on an Ansible module similar to those found at [this collection](https://github.com/adhawkins/ansible-borgbase), and managing the CSRF-based authentication of Auth.js through Python was turning out to be an impossible task (at least for me).

**Comment by deved99** [comment]
Hi!

I'm using BorgWarehouse and I'm liking it so far. I'd like to have some kind of daily report about the status of the Borg repositories.

I've seen that I can get the status of the repositories with the endpoint `{borgwarehouse_url}/api/repo`. I'm not sure how I can authenticate and I guess that this change would make it easier for me instead of authenticating via NextAuth.js.

Also, I could read the repo.json file from the config directory, but I would prefer using the API.

Any suggestions?

**Comment by Ravinou** [comment]
It's coming soon : 

![image](https://github.com/user-attachments/assets/33dfdb58-d0b7-4afe-8198-8aeb730640ad)

**Comment by Ravinou** [comment]
[Published in latest release.](https://github.com/Ravinou/borgwarehouse/releases/tag/v2.4.0)
