### ISSUE TITLE
Can't login via HTTP // Works through reverse proxy with TLS

### ISSUE THREAD

**Issue by shadowking001** [Ravinou/borgwarehouse#22]
Hello,

I can't login on HTTP page. Typing credentials and clicking "Login" just refresh the page.

![bwh_login_plain_http](https://user-images.githubusercontent.com/43928955/216769561-cc13f88c-72b1-4277-a332-a07c0fe94b78.PNG)

No error in the browser. And I can't find any log, where are they located ?

Going through my reverse proxy is functional though :

![bwh_login_ssl](https://user-images.githubusercontent.com/43928955/216769616-7e068754-0c5b-4ae2-afe6-a81ceac4d940.PNG)

Maybe I missed a warning about BWH not working through HTTP.

**Comment by Ravinou** [comment]
For me this is a normal behavior of the application. Indeed, in your local environment variable, you specify `NEXTAUTH_URL`. I guess you have specified the URL of your reverse proxy `bwh.****.ovh` ? 

**So, if you try to connect via another URL, then the authentication will necessarily fail.**

**It's not an HTTP/HTTPS issue**, it's because you must go to BorgWarehouse through the URL specified in the environment variable at build time because the JWT token that is generated depends on this URL.

I hope this is understandable for you. Let me know ;)
