### ISSUE TITLE
[BUG] Quota not updating in WebUI

### ISSUE THREAD

**Issue by mirisbowring** [Ravinou/borgwarehouse#247]
Hi,

i created a Repo via the UI and did an initial Backup via the command line to the server.
Everything works like a charm, data is backed up and i can access it.

Unfortunately the WebUI does not show how much of the Quota has been used:
<img width="1162" alt="image" src="https://github.com/Ravinou/borgwarehouse/assets/15715080/c096ed96-2984-4237-86dc-6a81aa7c505d">

When i hover the bar it is still 0% though 5GB has already been used.

I have the docker compose running on Unraid and compiled it with a different user (since 1001 is already used by someone)

Have a nice Day!

**Comment by Ravinou** [comment]
Hi, did you set the cron ? Check the doc [here.](https://borgwarehouse.com/docs/admin-manual/docker-installation/#scheduled-tasks)

**Comment by mirisbowring** [comment]
Man RTF! 😄 
Sry i just forgot about that part! I've put the two calls into a user script and now it works like a charm!

Would it be possible to call those jobs after a backup instead of a cronjob basis?
My disks are spinning down usually and i don't want to wake them regularly just for this check. Ideally, My Backup would finish and then this scripts get called

**Comment by Ravinou** [comment]
It's true that the documentation I've produced is an enormous amount of work, so I like to know that it's read and that it's not there for nothing. But it's been a long time since I've seen an RTFM, thanks for making me laugh haha 😄

To answer your question, I have no way of knowing when a backup ends at the borgwarehouse level. Your backup is end-to-end encrypted. But you can set your BorgBackup client to call the URL at the end if you wish. In short, there are quite a few solutions for this, which is also why the cron was taken out of BorgWarehouse, so you're free to use it as you see fit ;)

**Comment by mirisbowring** [comment]
Ah, i found a working solution for this.... I also have running borg serve on another machine and there i am using ssh forced commands (like you). I just added the refresh after the server:

```
command="borg serve ... ; curl api/refresh",restrict <public-key>
```

and it is working like a charm.
How can I modify the commands of BorgWarehouse?
Or would you be willed to add an option for this to the repos (like the append only or lan thing)?
