### ISSUE TITLE
user.json not created

### ISSUE THREAD

**Issue by BastLeblanc** [Ravinou/borgwarehouse#27]
I followed the debian deploy (raspberry pi) https://borgwarehouse.com/docs/admin-manual/debian-installation/

But I don't have any users.json generated, so can't login:

```
~/borgwarehouse $ find config/
config/
config/.gitkeep
```

Should I generate this file? I seems it should be created if it doesn't exist?

**Comment by Ravinou** [comment]
Hi @BastLeblanc 👋 ! 
The file `users.json` is created automatically on the first login. It's normal if it doesn't exist if you still haven't tried to log in. 
After a fresh install, login to BorgWarehouse with the **admin** login and the **admin** password. You can then change the password and login from the account settings.

**It is not because the file does not exist after the installation that you cannot connect to it. The admin/admin login will work if your file does not exist.**

Have you tried to connect with admin/admin ?

To get more informations about account : https://borgwarehouse.com/docs/user-manual/account/

**Comment by BastLeblanc** [comment]
thanks for the reply. admin/admin was failing yes.

It was not a users.json issue, it was a host/dns issue:

I connect to the http://ip:3000 to login, but it was redirecting to the DNS NEXTAUTH_URL which I set in the /home/borgwarehouse/borgwarehouse/.env.local file.
But this DNS was not set yet for reverseproxying... 

Adding the DNS + reverseproxy to IP:3000, I could login with admin/adin
