### ISSUE TITLE
/var/borgwarehouse hardcoded

### ISSUE THREAD

**Issue by BastLeblanc** [Ravinou/borgwarehouse#28]
Hi, is seems that /var/borgwarehouse is hardcoded, do you have any plans to make it:
- customizable (in .env.local ) ?
- import existing repositories in a different mount (for users who already have borg repo and looking for a gui) ?

**Comment by Ravinou** [comment]
I think you should be able to use a **symbolic link** if you want to store the repository somewhere else than in /var/borgwarehouse. I plan to review this, but not immediately.

For the import, I have planned a documentation rather than a real import function. I haven't done it yet. The easiest way if you have existing repo's is to choose an option :
- create a new repo with BorgWarehouse and start from scratch (then delete the old repo a few weeks later when you have enough history)
- create a new repo with BorgWarehouse and rsync the old repository to the new one. Be careful to reapply the user rights after the rsync though.
I plan to write a documentation for that, I didn't have the time yet :/

**Comment by Ravinou** [comment]
Hi, documentation are now created : 
- [Import an old BorgBackup repository into BorgWarehouse](https://borgwarehouse.com/docs/admin-manual/import-old-repo/)
- [The question about the /var/borgwarehouse directory](http://localhost:1313/docs/help/faq/#can-i-change-the-directory-varborgwarehouse-)
