### ISSUE TITLE
[Feature Request] Browsing repo contents and download files

### ISSUE THREAD

**Issue by callumgare** [Ravinou/borgwarehouse#33]
Thanks for a fantastic project! A good well maintained self-hostable webui has long been something I've felt is missing when it comes to borg so I was really happy to find this.

One feature I'd love to see at some point is the ability to browse the contents of repos at different points in time and download files from those repos. Have systems in place like backup failure notification is really import for ensure data is reliably backed up but backups are only as helpful as the process of restoring. When something goes wrong and I accidentally delete an important file or something, being able to quickly and painlessly restore that file really valuable. Adding a UI for restoring files makes restoring easier which means you're more likely to try it out more often which helps build confidence that you can actually trust your backups.

Thanks for your consideration :)

**Comment by Ravinou** [comment]
Hi @callumgare !
Sorry for the delay in answering (new job...) and first of all I thank you very much for this first sentence, it's a real pleasure to read it and as I often say this kind of comment is my fuel to continue ☺

For your question about the ability to browse the content of a repo, as I said in [documentation](https://borgwarehouse.com), BorgWarehouse is based on BorgBackup and **only handles the server side**. Your backups remain encrypted from end to end by your Borg client.

BorgBackup can be self-hosted but it can also be hosted on servers where you do not control the environment (physical and hardware). That's why BorgWarehouse was developed to maintain the highest level of confidentiality while allowing you to lighten and simplify the tasks involved in managing repositories.

However, did you see that I dedicated a part of the SetupWizard menu to data verification/recovery?

**You just have to select your repository and the commands are ready to be copied in one click**🎉, allowing you to verify or mount the data directory to retrieve files.

![image](https://user-images.githubusercontent.com/39600829/228202488-c330099d-8aa5-4ee8-a73c-e90b86c8b0fd.png)

Finally, if you are backing up a PC with a graphical interface, I recommend the Vorta client software, which also allows you to mount a Borg backup in a few clicks in order to retrieve its contents.

As you can see, I prefer BorgWarehouse to be agnostic and only the client side can access the decrypted data.

I hope my answer will help you and thank you again for your interest.

**Comment by Ravinou** [comment]
Can I close this issue @callumgare ?

**Comment by BrainStone** [comment]
Hey, so I think this functionality would be really great. This could be handled by passing the encryption keys to the UI (manually of course), so that the data could be viewed.

**Comment by callumgare** [comment]
@Ravinou  Sorry I'm only replying several years later! That all makes sense. Your commitment to user privacy is appreciated and definably gives me extra confidence in BorgWarehouse. And I hadn't seen the verification page as part of the wizard. That's a nice :)

Although personally if there were a totally optional separate part of the app where you could provide chose to provide your creds to BorgWarehouse in exchange for being able to browse your backups for me that wouldn't less my impression of BorgWarehouse's commitment to privacy. I mostly backup a bunch of servers and if I accidental mess up some random config file I'd be really nice to quickly pop into BorgWarehouse and grab that file rather than trying to remember/google the specific borg commands to extract that file. I think that's once place where a GUI has a bunch of advantages compared to it's cli equivalents. For example if you've navigated to specific as well as previewing that file the UI could do things like provide controls to quickly flip back though previous versions (helpful when you're not sure exactly when a file got screwed up).

But that would definably be distinctly larger scope than what BorgWarehouse is currently going for so totally understand if you want to avoid going into that side of things and happy to keep it closed. Thanks again for your work building and maintaining BorgWarehouse!
