### ISSUE TITLE
Suggestion: Switching to single backup user

### ISSUE THREAD

**Issue by apiening** [Ravinou/borgwarehouse#47]
It looks like the fact that **Borgwarehouse** creates **users** dynamically is an issue that kind of blocks **Docker** support (See https://github.com/Ravinou/borgwarehouse/issues/3 or https://github.com/Ravinou/borgwarehouse/issues/19).
Since I believe that **Docker** support is one key feature I want to share an alternative approach on how **BorgBackup** can be used with one single user on the backup server, securely.

- Create a user on the server / or in the container that is used for the remote backups . It can be named `borgwarehouse` or anything else, I'll chose `borgbackup` as the user name in this example. The `home` should be set to the base-dir, where all backups are stored in a subfolder named `repos`. Let's choose `/data/borgbackups` as a home.
- Wee need to add a configuration line to the file `/data/borgbackups/.ssh/authorized_keys` for every connecting client, like this:
```bash
command="cd /data/borgbackups/repos/USERNAME;borg serve --restrict-to-path /data/borgbackups/repos/USERNAME",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc SSHKEY
```
- The repository URL that is used by the clients to push their backup would then look like this:
```bash
ssh://borgbackup@BACKUPSERVER.MYDOMAIN.COM:repos/USERNAME
```

Explanation: The `command` parameter in the `authorized_keys` file restricts the given SSH-Public-Key to the user specific folder. The string **USERNAME** has to be replaced with the real username in both occurrences. The other options are limiting the usage to borg backup by disabling **port forwarding** etc. The string **SSKEY** is the public key used by this user.

I should say that this is not a crazy idea invented by me. This is based on an example from the official documentation of Borg (see https://borgbackup.readthedocs.io/en/stable/deployment/central-backup-server.html). I'm using this setup for 7 years and it works exactly the way I want.

Beside the fact that this does only require one user, I think it is actually pretty secure and it does make user management easier. For a new user, there is just one line required in the `authorized_keys` file and disabling or deleting this user can be done by simply removing this line.
It should be easier to manage permissions as well, since all borg repositories are belonging to one user-id.

With this setup it should be much simpler to create a docker image.

What do you think about this suggestion?

**Comment by philipkozeny** [comment]
Great idea, I would also favour that approach over creating system user accounts tbh. I am also using a very similar setup on my borg servers running since years.

**Comment by Ravinou** [comment]
Thank you very much for your suggestion. I've been thinking for a while about how to meet a need that many people have: using borgwarehouse with docker.

All the solutions I've looked at so far have been to try to create a VM with docker. And that's not the point... . In fact, the problem I'm having today isn't running BorgWarehouse, but managing several unix users with Docker.

Docker doesn't allow this, and there are certainly good security reasons for not trying to get around it.

So your idea seems very pertinent to me, and what's more, it's based on the BorgBackup documentation and your experience is interesting.

So I think I'm going to go down this route, but it's bound to be a breaking version (2.0) and I'll have to come up with a migration solution for existing users... In short, a lot of work :D

But I'm motivated to test and understand how BorgBackup works in this context, and adapting BorgWarehouse shouldn't be too complicated.

I'm currently on vacation, but I'll start looking into it in the next few weeks.

**Comment by apiening** [comment]
Thank you very much for your feedback @Ravinou, that's great to hear.

You're right with your statement that this would be a breaking change. However, the borg repositories on disk are still the same, they just needs to be moved from the home folders of the users to the new location and the ownership has to be changed recursively afterwards.
So once the new version supports the new repository structure, existing borg backups could be moved to the new location and there will be no loss regarding the backup history.
The **URL** would be different, but that's the only thing that has to be updated on the client side.

I have not yet tried **BorgWarehouse**, but I have seen the Video from https://borgwarehouse.com/docs/prologue/introduction/ and I do like the web interface. From what I can see the **Add a repository** dialog does not have to be changed that much because all that is required is already there: The **alias** and the **SSH public key**. But I don't know how the **Storage size** quota is implemented and I have not used this before.

I have not a lot of time to spare but I would love to get this going and would like to support you with testing for example. I also do have some experience with Docker, so maybe I can assist you at some point.

**Comment by Ravinou** [comment]
I remembered one of the reasons why I had chosen to work with several unix users. Simply because with a single unix user, you can't apply several quotas to a single SSH key that would be used on several repo ( [see this issue](https://github.com/borgbackup/borg/issues/7757) ).

BorgBackup's design with a single unix user (necessary if I want to make BorgWarehouse and Docker compatible) forces me to choose between :
- give up borg quota.
- prevent the same SSH key from being used on several repo.

What's your opinion on this @apiening @philipkozeny @YoSiJo @Pimmetje  ?

**Comment by apiening** [comment]
I kind of commented on this topic in another diskussion (see https://github.com/borgbackup/borg/issues/7757#issuecomment-1667572679).

I would be perfectly fine with quotas on a per SSH identity (public key) base.

**Comment by Ravinou** [comment]
I'm agree with [your comment ](https://github.com/borgbackup/borg/issues/7757#issuecomment-1667572679)  and after thinking about it today, I don't want to give up on quotas, because they're useful and an essential part of BorgWarehouse.

What's more, one of BorgBackup's developers suggests that it's not impossible that they'll allow the quota flag to be used more than once in the future. Perhaps they will implement this in BorgBackup v2 ... 🤞

In any case, I'm going to go this way and limit the use of an SSH key to a single repository. Thanks for your contribution @apiening

**Comment by Pimmetje** [comment]
For security sake i would keep the separation. I would only suggest use ansible for account creation and don't bother with shell scripts. On a plus side this would work for docker/ubuntu/centos/alpine or whatever ansible supports without needing to make any or very little code changes.

Just my 2 cents :)

**Comment by philipkozeny** [comment]
If you use separate SSH keys for each repository, it's feasible to set a quota per repo. Currently, I use this approach for our servers and clients. Off the top of my head, I can't find a compelling reason to reuse an SSH key across different clients or a reason to have multiple repos in one backup location from one device. Therefore, having a unique SSH key for each repo (and corresponding quotas) aligns with our existing practices.

**Comment by Pimmetje** [comment]
> In the end, imho, with a single UNIX user and a much smaller sudoers file, the attack surface is considerably reduced, which I think is better for security.

If u use ansible no sudo file is needed. Only one command is deeded (do a ansible run).  Ansible in itself can read a yaml file with all the users it has to create. Given the structure van be static no more than the username & SSH key is needed for ansible to figure out the rest.
Sure borg should keep it separate. But it would add a extra layer if u use multiple users.

**Comment by Ravinou** [comment]
Hi everyone, I've made great progress on borgwarehouse v2.0 and version [v2.0.0-rc3.0](https://github.com/Ravinou/borgwarehouse/releases/tag/v2.0.0-rc.3) is now fully functional on Docker ! 

The next steps for me before releasing this v2.0 are : 
- updating the [borgwarehouse](https://borgwarehouse.com/) documentation
- writing a procedure to help you move from v1 to v2

**Once this v2 has been published, I'll be able to get back to work on future features for borgwarehouse!**

If you'd like to test the Docker version, since there's no real documentation yet, you can do so by following these few lines:

You can choose the user of your choice to run this container (this is not a root container), but bear these constraints in mind : 
- the user must have a UID/GID other than 1000 (this UID is taken by node in the container), you are free to put in 1001 and 10000.
- The 4 data volumes must belong to this UID/GID.
- Git pull the [v2.0 branch](https://github.com/Ravinou/borgwarehouse/tree/v2.0).
- Edit the `docker-compose.yml` with your own env vars (the env vars in the sample is the minimal to have).
- Launch it with : `docker compose up`

Stay tuned !

**Comment by Ravinou** [comment]
Hi, this it ! This major rewrite for Docker is done. I'm pretty proud of the many evenings and Saturdays I've spent working on BorgWarehouse, and I hope you enjoy this version. 

You will find : 
- The release v2.0.0 [here](https://github.com/Ravinou/borgwarehouse/releases/tag/v2.0.0)
- The updated documentation on [borgwarehouse.com](https://borgwarehouse.com)
- The specific page about docker installation [here](https://borgwarehouse.com/docs/admin-manual/docker-installation/)

To give me strength, I can only invite you to consider [**github sponsor**](https://github.com/sponsors/Ravinou) (one-time/monthly), and **talk about BorgWarehouse**. It keeps me going!

Have fun with docker 🚀
