### ISSUE TITLE
can't login to panel

### ISSUE THREAD

**Issue by UnixxSH** [Ravinou/borgwarehouse#54]
I've tried two installations by following exactly the instructions at https://borgwarehouse.com/docs/admin-manual/debian-installation/, including one on a fresh Debian install (bookworm).

The default admin credentials are not working, no error message. 'Sign in' juste do a little animation, nothing else. I can't find any useful logs (I'm not used to npm).

Does someone have an idea ?

**Comment by Ravinou** [comment]
Hi ! 😀

Are you on the latest release 1.6.0 ? (Don't use 2.0, it's not ready for production again).

If you use the latest release :
- if the file config/users.json not exist, it will be created with default admin/admin.
- if default admin/admin not work, it generally due to bad implementation of env variables in .env.local and the NEXTAUTH_URL in particular. **If you didn't implement TLS, don't use "https" but "http".**

https://borgwarehouse.com/docs/admin-manual/debian-installation/#configure-application-environment-variables

This issue can help you :[ https://github.com/Ravinou/borgwarehouse/issues/27](https://github.com/Ravinou/borgwarehouse/issues/27)

Let me know if it's okay for you and if it's not, i will need more information (log or value on some var in env file).

**Comment by UnixxSH** [comment]
> Are you on the latest release 1.6.0 ? (Don't use 2.0, it's not ready for production again).

I'm well using last relase 1.6.0.

> * if default admin/admin not work, it generally due to bad implementation of env variables in .env.local and the NEXTAUTH_URL in particular. **If you didn't implement TLS, don't use "https" but "http".**

oof, you are right, there was a misconf with my var NEXTAUTH_URL (I was using https while I didn't configured tls yet...). that's working fine now !

By the way, do you have a way to check the logs of your application if needed ?

Many thank's for your reply, and your work !

**Comment by Ravinou** [comment]
Nice :) 

For the logs, if you use the systemd service, just check the log for it. For example for live follow : 

```
journalctl -f -u borgwarehouse
```

Have a good day and thank you very much for your words of encouragement ♥
